name: Deploy to neocities

# only run on changes to master
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to neocities"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Set up any tools and build steps here
      # This example uses a Node.js toolchain to build a site
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - name: Install deps and build
        run: |
          npm i
          npm run build
      # When the dist_dir is ready, deploy it to neocities
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{secrets.NEOCITIES_TOKEn}}
          cleanup: true
          dist_dir: _site
